### ISSUE TITLE
Does not work?

### ISSUE THREAD

**Issue by screendriver** [alfg/hyperterm-retro#1]
I added `hyperterm-retro` to my `~/hyper.js` but nothing happens after I reload the terminal? 🤔

**Comment by screendriver** [comment]
Sorry, you have to **close** and re-open the terminal. Then it works 😎

**Comment by alfg** [comment]
Yeah, gotta restart or reload the terminal for it to apply.

**Comment by screendriver** [comment]
Reload didn't work in my case 😉
